"""Synthetic electoral graph generator.

Lets the whole pipeline (ingestion -> simulation -> visualization) be exercised
and tested without real TSE files or shapefiles on disk. Adjacency is built from
a Delaunay triangulation of random points, which -- like real canton borders --
yields a sparse, roughly-planar graph (~6 neighbors/node on average) rather than
an unrealistic fully-connected or regular-lattice graph. "Empirical" spins are
generated by relaxing the same graph with our own Glauber dynamics at low
temperature, so the synthetic ground truth has the spatially-clustered structure
real electoral maps show, instead of i.i.d. noise.
"""

from __future__ import annotations

import itertools

import networkx as nx
import numpy as np
import scipy.sparse as sp
from scipy.spatial import Delaunay

from ..simulation.ising_model import IsingModel
from ..simulation.monte_carlo import run_mc


def synthetic_electoral_graph(n_units: int = 84, seed: int = 0, low_T: float = 0.5,
                               n_relax_sweeps: int = 100, field_scale: float = 0.0) -> nx.Graph:
    """Build a fake but structurally realistic electoral adjacency + results graph.

    Parameters
    ----------
    n_units : number of geographic units (default 84, matching Costa Rica's canton count).
    seed : RNG seed for reproducibility.
    low_T : temperature used to relax the synthetic "empirical" spin pattern into
        spatially clustered domains (lower = larger, more contiguous clusters).
    n_relax_sweeps : number of Glauber sweeps used for that relaxation.
    field_scale : if > 0, adds a smooth spatial field h_i = field_scale * (x_i - 0.5),
        a linear "regional mood" gradient standing in for top-down influence/incumbency
        bias. A smooth gradient (rather than i.i.d. per-node noise) breaks the model's
        up/down (Z2) symmetry -- which real elections don't have, but a symmetric h=0
        Ising model does -- without turning the graph into a disordered/glassy random-
        field system, which would make the low-T ground state history-dependent.

    Returns
    -------
    networkx.Graph with node attributes "code", "name", "pos", "h", "spin_empirical"
    and edge attribute "weight" -- the same shape `build_electoral_graph` produces
    from real data, so it's a drop-in for `graph_to_arrays` and the visualization layer.
    """
    rng = np.random.default_rng(seed)
    points = rng.random((n_units, 2))
    tri = Delaunay(points)

    G = nx.Graph()
    for i in range(n_units):
        G.add_node(i, pos=(float(points[i, 0]), float(points[i, 1])))
    for simplex in tri.simplices:
        for a, b in itertools.combinations(simplex, 2):
            G.add_edge(int(a), int(b), weight=1.0)

    rows, cols, data = [], [], []
    for u, v, d in G.edges(data=True):
        rows += [u, v]
        cols += [v, u]
        data += [d["weight"], d["weight"]]
    J = sp.csr_matrix((data, (rows, cols)), shape=(n_units, n_units))
    h = field_scale * (points[:, 0] - 0.5) if field_scale > 0 else np.zeros(n_units)

    model = IsingModel(J, h, rng=rng)
    result = run_mc(model, T=low_T, n_equil=n_relax_sweeps, n_sweeps=1,
                     dynamics="glauber", rng=rng)
    empirical_spins = result["final_spins"]

    for i in range(n_units):
        code = f"C{i:03d}"
        G.nodes[i]["code"] = code
        G.nodes[i]["name"] = f"Synthetic Canton {i}"
        G.nodes[i]["h"] = float(h[i])
        G.nodes[i]["spin_empirical"] = int(empirical_spins[i])

    return nx.relabel_nodes(G, {i: G.nodes[i]["code"] for i in G.nodes})
